packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false

overrides:
  "@esbuild-kit/core-utils>esbuild": "0.28.2"

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - workerd
